name = "easytier"
main = "src/index.ts"
compatibility_date = "2026-04-05"

[placement]
mode = "smart"

[[containers]]
name = "easytier-mycontainer"
class_name = "EasyTierContainer"
image = "docker.io/easytier/easytier:v2.5.0"
instance_type = "basic"
max_instances = 100

[[durable_objects.bindings]]
name = "EASYTIER_CONTAINER"
class_name = "EasyTierContainer"

[[durable_objects.bindings]]
name = "NETWORK_ROUTER"
class_name = "NetworkRouter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyContainer"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["NetworkRouter"]

[[migrations]]
tag = "v3"
renamed_classes = [
  { from = "MyContainer", to = "EasyTierContainer" }
]

[observability.logs]
enabled = true

[[routes]]
pattern = "et.icewhale.io"
zone_name = "icewhale.io"
custom_domain = true
