name = "easytier"
main = "src/index.ts"
compatibility_date = "2026-04-05"

[placement]
mode = "smart"

[[containers]]
class_name = "MyContainer"
image = "docker.io/easytier/easytier:v2.5.0"
instance_type = "basic"
max_instances = 1

[[durable_objects.bindings]]
name = "EASYTIER_CONTAINER"
class_name = "MyContainer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyContainer"]

[observability.logs]
enabled = true

[[routes]]
pattern = "et.icewhale.io"
zone_name = "icewhale.io"
custom_domain = true
